sudo: true

services:
    - docker
    
script:
    - docker build -t cuppajavamattis/currency-exchange-service:latest -f Dockerfile.dev .
    - docker push cuppajavamattis/multi-currency-exchange:latest
    
deploy:
    provider: "elasticbeanstalk"
    region: "us-east-2"
    app: "mattiz-again"
    env: "MattizAgain-env"
    bucket_name: "elasticbeanstalk-us-east-2-066501592116"
    bucket_path: "mattiz-again"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY