sudo: true

services:
    - docker
    
script:
    - docker build -t cuppajavamattis/currency-exchange-service:latest -f Dockerfile.dev .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push cuppajavamattis/currency-exchange-service:latest

    
deploy:
    provider: "elasticbeanstalk"
    region: "us-east-2"
    app: "matt-natt"
    env: "MattNatt-env"
    bucket_name: "elasticbeanstalk-us-east-2-066501592116"
    bucket_path: "matt-natt"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY