# fetch basic image
FROM maven:3.3.9-jdk-8

# application placed into /opt/app
RUN mkdir -p /opt/app
WORKDIR /opt/app

# selectively add the POM file and
# install dependencies
COPY pom.xml /opt/app/
RUN mvn clean test install

# rest of the project
COPY src /opt/app/src
RUN mvn package

# local application port
EXPOSE 8001


# execute it
CMD ["java","-jar","/opt/app/target/currency-exchange-service-0.0.1.jar"]